name: frontend
type: "nodejs:20"

build:
  flavor: none

variables:
  env:
    NODE_OPTIONS: '--max-old-space-size=2048'

hooks:
  build: |
    set -e
    npm install
    npm run build
  deploy: |
    touch jsonconf/routes.json
    : > jsonconf/routes.json
    BACKEND_URL=$(echo $PLATFORM_ROUTES | base64 --decode | jq -r 'to_entries[] | select(.value.id=="backend") | .key')
    echo -n {\"url\": \"$BACKEND_URL\"} > jsonconf/routes.json

disk: 256 

mounts:
  'jsonconf':
    source: local
    source_path: jsonconf

web:
  commands:
    start: "npm start -- --port $PORT"
  upstream:
    socket_family: tcp
  locations:
    "/":
      root: "build"
      index: ["index.html"]
      scripts: false
      allow: true
    "/jsonconf":
      root: "jsonconf"
        

