name: backend
type: "java:17"

variables:
    env:
        MAVEN_VERSION: 3.9.6

relationships:
    database: "db:mysql"

hooks:
    build: |
        set -e
        mvn clean package

web:
    commands:
        start: java -jar $JAVA_OPTS target/demo-0.0.1-SNAPSHOT.jar --server.port=$PORT