name: backend
type: "java:17"

variables:
    env:
        MAVEN_VERSION: 3.9.6

relationships:
    database: "mariadb:mysql"

hooks:
    build: |
        set -e
        curl -sfLO "https://dlcdn.apache.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz"
        tar -zxf apache-maven-$MAVEN_VERSION-bin.tar.gz
        export PATH="$PWD/apache-maven-$MAVEN_VERSION/bin:$PATH"
        mvn --version
        mvn clean package

web:
    commands:
      start: "java -jar $JAVA_OPTS target/demo-0.0.1-SNAPSHOT.jar --server.port=$PORT; sleep 60"
    upstream:
      socket_family: tcp
    locations:
      "/":
        passthru: true